### ISSUE TITLE
onLoadResource Causing Loading Issues

### ISSUE THREAD

**Issue by jacobacon** [pichillilorenzo/flutter_inappbrowser#38] opened 2019-01-14 02:53 UTC
I noticed that when the "useOnLoadResource" option is enabled on Android, the page fails to load completely in the InAppBrowser

I initially thought it was an issue with my onLoadResource function, but noticed this behavior is consistent with a clean project and the built-in "dummy" onLoadResource function.

`floatingActionButton: FloatingActionButton(
        onPressed: () {
          inAppBrowser.open(
              url: "https://www.google.com",
              options: {"useOnLoadResource": false});
        },
        tooltip: 'Increment',
        child: Icon(Icons.add),
      ), `

As you can see google.com is render with normal CSS as expected.

![image](https://user-images.githubusercontent.com/1043389/51094588-f4f6be80-1773-11e9-847e-26076b9d8a91.png)

`

Now the only thing I changed was enabling onLoadResource, without even @overriding the built in method.

floatingActionButton: FloatingActionButton(
        onPressed: () {
          inAppBrowser.open(
              url: "https://www.google.com",
              options: {"useOnLoadResource": true});
        },
        tooltip: 'Increment',
        child: Icon(Icons.add),
      ), 
`
Here you can see google.com doesn't render properly, with the wrong scaling and missing style on the top buttons.

![image](https://user-images.githubusercontent.com/1043389/51094664-88c88a80-1774-11e9-8640-9634cb5ab496.png)

I've tried downgrading my version, and the issue still exists, and is not present at all on iOS.

**Comment by pichillilorenzo** [comment] 2019-01-14 10:35
Ok, I will check about that! Thanks

**Comment by alsocalledchris** [comment] 2019-02-12 13:45
@pichillilorenzo I'm having this issue on Android as well - it has different behaviour with the option enabled and disabled even if you have no actions - doesn't seem to affect every page shown - just some?

**Comment by pichillilorenzo** [comment] 2019-03-11 02:59
@alsocalledchris the problem is here: https://github.com/pichillilorenzo/flutter_inappbrowser/blob/a1e3011087119570e16b8caa9176aacabe46924e/android/src/main/java/com/pichillilorenzo/flutter_inappbrowser/InAppWebView/InAppWebViewClient.java#L363
I don't know why it works in same pages and in same not.

However, now the function returns `null` so should be fixed with the new version **0.6.0**, but I don't like this fix very much.

**Closed by pichillilorenzo** 2019-03-11 02:59 UTC
